### ISSUE TITLE
Does not complete

### ISSUE THREAD

**Issue by AtomicNess123** [dunn/company-emoji#10]
Upon installation (just require line, installed via Melpa), I type ( :cat however, not list of autocompletion shows up :(

**Comment by tigermonkey** [comment]
This happens for me as well. However it depends on the starting letter I think. For example with `:c` I get no completion menu, but with `:g` I do

**Comment by c-alpha** [comment]
Same here (Emacs 27.1, `company-mode` 20200813.2229, `company-emoji` 20200612.1902).

When I type `:`, the very first completion candidate I get is `:grinning:`, which happens to be the first entry in the list returned by `company-emoji-list-create`. Since completion candidates are sorted alphabetically, this means that all emojis starting with the letters `a` through `f` (inclusive) are not accessible.

Maybe somehow emoji-list, which is generated in [line 195](https://github.com/dunn/company-emoji/blob/5f2d10623c1e9f547d852cb13c7a391afbda09fb/company-emoji.el#L195), seems to not be what it should? Didn't debug, so just guessing here.

**Comment by dunn** [comment]
Sorry I didn't get to this for so long.  I'm trying to reproduce it now and having trouble.  `:a` works for me, though to be fair it takes a bit of time, because the emoji list is so long.  If it never actually loads for you, is there any debug or error message?

https://github.com/dunn/company-emoji/pull/13 was opened to address this, but now I'm not sure if it's necessary.

cc @tonyaldon

**Comment by YellowApple** [comment]
I'm experiencing the same issue (well, closer to what's described in #14, where candidates before `:grinning:` are present exactly once and then disappear).  Either of the following two approaches in my `~/.emacs` seem to do the trick in resolving the issue for me:

```elisp
;; Approach in PR #13 
(require 'dash) ; assuming it's installed
(defconst company-emojis (-sort 'string-lessp (company-emoji-list-create)))

;; Bypass aliases and in-constant caching entirely
(defun company-emoji--add-aliases (aliases candidates) (company-emoji-list-create))
```

**Comment by dunn** [comment]
if the first fix is just sorting the list, can you try manually sorting the list in company-emoji-list.el and see if that helps?  if it does, i can just add a step to the generator to sort it

**Comment by mattford63** [comment]
I manually sorted the list and everything started working :smile:

**Comment by mattford63** [comment]
Also though the aliases don't work for me, so perhaps they need to be inserted in order?

**Comment by dunn** [comment]
@mattford63 thanks for checking! i'll make the change

**Comment by dunn** [comment]
tagged as 2.6.1, let me know if you're still seeing problems

**Comment by tigermonkey** [comment]
I just checked and it's working for me. Thanks!

**Comment by dunn** [comment]
great! i'll close this, but lmk if there's any lingering problems
